/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BEService_CONSTANTS_H
#define BEService_CONSTANTS_H

#include "BEService_types.h"



class BEServiceConstants {
 public:
  BEServiceConstants();

};

extern const BEServiceConstants g_BEService_constants;



#endif
