/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "BEService_constants.h"



const BEServiceConstants g_BEService_constants;

BEServiceConstants::BEServiceConstants() {
}



